// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package deployment

import (
	"context"
	"sync"

	"github.com/goevery/sunstone/internal/modules/deployment/internal/features/deploy"
)

// Ensure that mockLoader does implement deploy.Loader.
// If this is not the case, regenerate this file with mockery.
var _ deploy.Loader = &mockLoader{}

// mockLoader is a mock implementation of deploy.Loader.
//
//	func TestSomethingThatUsesLoader(t *testing.T) {
//
//		// make and configure a mocked deploy.Loader
//		mockedLoader := &mockLoader{
//			LoadFunc: func(s string) (deploy.Workload, error) {
//				panic("mock out the Load method")
//			},
//		}
//
//		// use mockedLoader in code that requires deploy.Loader
//		// and then make assertions.
//
//	}
type mockLoader struct {
	// LoadFunc mocks the Load method.
	LoadFunc func(s string) (deploy.Workload, error)

	// calls tracks calls to the methods.
	calls struct {
		// Load holds details about calls to the Load method.
		Load []struct {
			// S is the s argument value.
			S string
		}
	}
	lockLoad sync.RWMutex
}

// Load calls LoadFunc.
func (mock *mockLoader) Load(s string) (deploy.Workload, error) {
	if mock.LoadFunc == nil {
		panic("mockLoader.LoadFunc: method is nil but Loader.Load was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockLoad.Lock()
	mock.calls.Load = append(mock.calls.Load, callInfo)
	mock.lockLoad.Unlock()
	return mock.LoadFunc(s)
}

// LoadCalls gets all the calls that were made to Load.
// Check the length with:
//
//	len(mockedLoader.LoadCalls())
func (mock *mockLoader) LoadCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockLoad.RLock()
	calls = mock.calls.Load
	mock.lockLoad.RUnlock()
	return calls
}

// Ensure that mockConnector does implement deploy.Connector.
// If this is not the case, regenerate this file with mockery.
var _ deploy.Connector = &mockConnector{}

// mockConnector is a mock implementation of deploy.Connector.
//
//	func TestSomethingThatUsesConnector(t *testing.T) {
//
//		// make and configure a mocked deploy.Connector
//		mockedConnector := &mockConnector{
//			ConnectFunc: func(context1 context.Context, target deploy.Target, s string) (deploy.Host, error) {
//				panic("mock out the Connect method")
//			},
//		}
//
//		// use mockedConnector in code that requires deploy.Connector
//		// and then make assertions.
//
//	}
type mockConnector struct {
	// ConnectFunc mocks the Connect method.
	ConnectFunc func(context1 context.Context, target deploy.Target, s string) (deploy.Host, error)

	// calls tracks calls to the methods.
	calls struct {
		// Connect holds details about calls to the Connect method.
		Connect []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// Target is the target argument value.
			Target deploy.Target
			// S is the s argument value.
			S string
		}
	}
	lockConnect sync.RWMutex
}

// Connect calls ConnectFunc.
func (mock *mockConnector) Connect(context1 context.Context, target deploy.Target, s string) (deploy.Host, error) {
	if mock.ConnectFunc == nil {
		panic("mockConnector.ConnectFunc: method is nil but Connector.Connect was just called")
	}
	callInfo := struct {
		Context1 context.Context
		Target   deploy.Target
		S        string
	}{
		Context1: context1,
		Target:   target,
		S:        s,
	}
	mock.lockConnect.Lock()
	mock.calls.Connect = append(mock.calls.Connect, callInfo)
	mock.lockConnect.Unlock()
	return mock.ConnectFunc(context1, target, s)
}

// ConnectCalls gets all the calls that were made to Connect.
// Check the length with:
//
//	len(mockedConnector.ConnectCalls())
func (mock *mockConnector) ConnectCalls() []struct {
	Context1 context.Context
	Target   deploy.Target
	S        string
} {
	var calls []struct {
		Context1 context.Context
		Target   deploy.Target
		S        string
	}
	mock.lockConnect.RLock()
	calls = mock.calls.Connect
	mock.lockConnect.RUnlock()
	return calls
}

// Ensure that mockHost does implement deploy.Host.
// If this is not the case, regenerate this file with mockery.
var _ deploy.Host = &mockHost{}

// mockHost is a mock implementation of deploy.Host.
//
//	func TestSomethingThatUsesHost(t *testing.T) {
//
//		// make and configure a mocked deploy.Host
//		mockedHost := &mockHost{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			CreateFunc: func(context1 context.Context, containerSpec deploy.ContainerSpec) (deploy.Container, error) {
//				panic("mock out the Create method")
//			},
//			LogsFunc: func(context1 context.Context, container deploy.Container) (string, error) {
//				panic("mock out the Logs method")
//			},
//			MatchesFunc: func(context1 context.Context, container deploy.Container, containerSpec deploy.ContainerSpec) (bool, error) {
//				panic("mock out the Matches method")
//			},
//			PullFunc: func(context1 context.Context, s string) (deploy.Image, error) {
//				panic("mock out the Pull method")
//			},
//			RemoveFunc: func(context1 context.Context, container deploy.Container) error {
//				panic("mock out the Remove method")
//			},
//			StartFunc: func(context1 context.Context, container deploy.Container) error {
//				panic("mock out the Start method")
//			},
//			StopFunc: func(context1 context.Context, container deploy.Container) error {
//				panic("mock out the Stop method")
//			},
//			VerifyFunc: func(context1 context.Context, container deploy.Container) error {
//				panic("mock out the Verify method")
//			},
//			WorkloadContainersFunc: func(context1 context.Context, s string) ([]deploy.Container, error) {
//				panic("mock out the WorkloadContainers method")
//			},
//		}
//
//		// use mockedHost in code that requires deploy.Host
//		// and then make assertions.
//
//	}
type mockHost struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// CreateFunc mocks the Create method.
	CreateFunc func(context1 context.Context, containerSpec deploy.ContainerSpec) (deploy.Container, error)

	// LogsFunc mocks the Logs method.
	LogsFunc func(context1 context.Context, container deploy.Container) (string, error)

	// MatchesFunc mocks the Matches method.
	MatchesFunc func(context1 context.Context, container deploy.Container, containerSpec deploy.ContainerSpec) (bool, error)

	// PullFunc mocks the Pull method.
	PullFunc func(context1 context.Context, s string) (deploy.Image, error)

	// RemoveFunc mocks the Remove method.
	RemoveFunc func(context1 context.Context, container deploy.Container) error

	// StartFunc mocks the Start method.
	StartFunc func(context1 context.Context, container deploy.Container) error

	// StopFunc mocks the Stop method.
	StopFunc func(context1 context.Context, container deploy.Container) error

	// VerifyFunc mocks the Verify method.
	VerifyFunc func(context1 context.Context, container deploy.Container) error

	// WorkloadContainersFunc mocks the WorkloadContainers method.
	WorkloadContainersFunc func(context1 context.Context, s string) ([]deploy.Container, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// ContainerSpec is the containerSpec argument value.
			ContainerSpec deploy.ContainerSpec
		}
		// Logs holds details about calls to the Logs method.
		Logs []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// Container is the container argument value.
			Container deploy.Container
		}
		// Matches holds details about calls to the Matches method.
		Matches []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// Container is the container argument value.
			Container deploy.Container
			// ContainerSpec is the containerSpec argument value.
			ContainerSpec deploy.ContainerSpec
		}
		// Pull holds details about calls to the Pull method.
		Pull []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// Container is the container argument value.
			Container deploy.Container
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// Container is the container argument value.
			Container deploy.Container
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// Container is the container argument value.
			Container deploy.Container
		}
		// Verify holds details about calls to the Verify method.
		Verify []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// Container is the container argument value.
			Container deploy.Container
		}
		// WorkloadContainers holds details about calls to the WorkloadContainers method.
		WorkloadContainers []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
		}
	}
	lockClose              sync.RWMutex
	lockCreate             sync.RWMutex
	lockLogs               sync.RWMutex
	lockMatches            sync.RWMutex
	lockPull               sync.RWMutex
	lockRemove             sync.RWMutex
	lockStart              sync.RWMutex
	lockStop               sync.RWMutex
	lockVerify             sync.RWMutex
	lockWorkloadContainers sync.RWMutex
}

// Close calls CloseFunc.
func (mock *mockHost) Close() error {
	if mock.CloseFunc == nil {
		panic("mockHost.CloseFunc: method is nil but Host.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedHost.CloseCalls())
func (mock *mockHost) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *mockHost) Create(context1 context.Context, containerSpec deploy.ContainerSpec) (deploy.Container, error) {
	if mock.CreateFunc == nil {
		panic("mockHost.CreateFunc: method is nil but Host.Create was just called")
	}
	callInfo := struct {
		Context1      context.Context
		ContainerSpec deploy.ContainerSpec
	}{
		Context1:      context1,
		ContainerSpec: containerSpec,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(context1, containerSpec)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedHost.CreateCalls())
func (mock *mockHost) CreateCalls() []struct {
	Context1      context.Context
	ContainerSpec deploy.ContainerSpec
} {
	var calls []struct {
		Context1      context.Context
		ContainerSpec deploy.ContainerSpec
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Logs calls LogsFunc.
func (mock *mockHost) Logs(context1 context.Context, container deploy.Container) (string, error) {
	if mock.LogsFunc == nil {
		panic("mockHost.LogsFunc: method is nil but Host.Logs was just called")
	}
	callInfo := struct {
		Context1  context.Context
		Container deploy.Container
	}{
		Context1:  context1,
		Container: container,
	}
	mock.lockLogs.Lock()
	mock.calls.Logs = append(mock.calls.Logs, callInfo)
	mock.lockLogs.Unlock()
	return mock.LogsFunc(context1, container)
}

// LogsCalls gets all the calls that were made to Logs.
// Check the length with:
//
//	len(mockedHost.LogsCalls())
func (mock *mockHost) LogsCalls() []struct {
	Context1  context.Context
	Container deploy.Container
} {
	var calls []struct {
		Context1  context.Context
		Container deploy.Container
	}
	mock.lockLogs.RLock()
	calls = mock.calls.Logs
	mock.lockLogs.RUnlock()
	return calls
}

// Matches calls MatchesFunc.
func (mock *mockHost) Matches(context1 context.Context, container deploy.Container, containerSpec deploy.ContainerSpec) (bool, error) {
	if mock.MatchesFunc == nil {
		panic("mockHost.MatchesFunc: method is nil but Host.Matches was just called")
	}
	callInfo := struct {
		Context1      context.Context
		Container     deploy.Container
		ContainerSpec deploy.ContainerSpec
	}{
		Context1:      context1,
		Container:     container,
		ContainerSpec: containerSpec,
	}
	mock.lockMatches.Lock()
	mock.calls.Matches = append(mock.calls.Matches, callInfo)
	mock.lockMatches.Unlock()
	return mock.MatchesFunc(context1, container, containerSpec)
}

// MatchesCalls gets all the calls that were made to Matches.
// Check the length with:
//
//	len(mockedHost.MatchesCalls())
func (mock *mockHost) MatchesCalls() []struct {
	Context1      context.Context
	Container     deploy.Container
	ContainerSpec deploy.ContainerSpec
} {
	var calls []struct {
		Context1      context.Context
		Container     deploy.Container
		ContainerSpec deploy.ContainerSpec
	}
	mock.lockMatches.RLock()
	calls = mock.calls.Matches
	mock.lockMatches.RUnlock()
	return calls
}

// Pull calls PullFunc.
func (mock *mockHost) Pull(context1 context.Context, s string) (deploy.Image, error) {
	if mock.PullFunc == nil {
		panic("mockHost.PullFunc: method is nil but Host.Pull was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
	}{
		Context1: context1,
		S:        s,
	}
	mock.lockPull.Lock()
	mock.calls.Pull = append(mock.calls.Pull, callInfo)
	mock.lockPull.Unlock()
	return mock.PullFunc(context1, s)
}

// PullCalls gets all the calls that were made to Pull.
// Check the length with:
//
//	len(mockedHost.PullCalls())
func (mock *mockHost) PullCalls() []struct {
	Context1 context.Context
	S        string
} {
	var calls []struct {
		Context1 context.Context
		S        string
	}
	mock.lockPull.RLock()
	calls = mock.calls.Pull
	mock.lockPull.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *mockHost) Remove(context1 context.Context, container deploy.Container) error {
	if mock.RemoveFunc == nil {
		panic("mockHost.RemoveFunc: method is nil but Host.Remove was just called")
	}
	callInfo := struct {
		Context1  context.Context
		Container deploy.Container
	}{
		Context1:  context1,
		Container: container,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	return mock.RemoveFunc(context1, container)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedHost.RemoveCalls())
func (mock *mockHost) RemoveCalls() []struct {
	Context1  context.Context
	Container deploy.Container
} {
	var calls []struct {
		Context1  context.Context
		Container deploy.Container
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *mockHost) Start(context1 context.Context, container deploy.Container) error {
	if mock.StartFunc == nil {
		panic("mockHost.StartFunc: method is nil but Host.Start was just called")
	}
	callInfo := struct {
		Context1  context.Context
		Container deploy.Container
	}{
		Context1:  context1,
		Container: container,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(context1, container)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedHost.StartCalls())
func (mock *mockHost) StartCalls() []struct {
	Context1  context.Context
	Container deploy.Container
} {
	var calls []struct {
		Context1  context.Context
		Container deploy.Container
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *mockHost) Stop(context1 context.Context, container deploy.Container) error {
	if mock.StopFunc == nil {
		panic("mockHost.StopFunc: method is nil but Host.Stop was just called")
	}
	callInfo := struct {
		Context1  context.Context
		Container deploy.Container
	}{
		Context1:  context1,
		Container: container,
	}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	return mock.StopFunc(context1, container)
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedHost.StopCalls())
func (mock *mockHost) StopCalls() []struct {
	Context1  context.Context
	Container deploy.Container
} {
	var calls []struct {
		Context1  context.Context
		Container deploy.Container
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}

// Verify calls VerifyFunc.
func (mock *mockHost) Verify(context1 context.Context, container deploy.Container) error {
	if mock.VerifyFunc == nil {
		panic("mockHost.VerifyFunc: method is nil but Host.Verify was just called")
	}
	callInfo := struct {
		Context1  context.Context
		Container deploy.Container
	}{
		Context1:  context1,
		Container: container,
	}
	mock.lockVerify.Lock()
	mock.calls.Verify = append(mock.calls.Verify, callInfo)
	mock.lockVerify.Unlock()
	return mock.VerifyFunc(context1, container)
}

// VerifyCalls gets all the calls that were made to Verify.
// Check the length with:
//
//	len(mockedHost.VerifyCalls())
func (mock *mockHost) VerifyCalls() []struct {
	Context1  context.Context
	Container deploy.Container
} {
	var calls []struct {
		Context1  context.Context
		Container deploy.Container
	}
	mock.lockVerify.RLock()
	calls = mock.calls.Verify
	mock.lockVerify.RUnlock()
	return calls
}

// WorkloadContainers calls WorkloadContainersFunc.
func (mock *mockHost) WorkloadContainers(context1 context.Context, s string) ([]deploy.Container, error) {
	if mock.WorkloadContainersFunc == nil {
		panic("mockHost.WorkloadContainersFunc: method is nil but Host.WorkloadContainers was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
	}{
		Context1: context1,
		S:        s,
	}
	mock.lockWorkloadContainers.Lock()
	mock.calls.WorkloadContainers = append(mock.calls.WorkloadContainers, callInfo)
	mock.lockWorkloadContainers.Unlock()
	return mock.WorkloadContainersFunc(context1, s)
}

// WorkloadContainersCalls gets all the calls that were made to WorkloadContainers.
// Check the length with:
//
//	len(mockedHost.WorkloadContainersCalls())
func (mock *mockHost) WorkloadContainersCalls() []struct {
	Context1 context.Context
	S        string
} {
	var calls []struct {
		Context1 context.Context
		S        string
	}
	mock.lockWorkloadContainers.RLock()
	calls = mock.calls.WorkloadContainers
	mock.lockWorkloadContainers.RUnlock()
	return calls
}
